### ISSUE TITLE
Unexpected Token error when trying to start music

### ISSUE THREAD

**Issue by siebsie23** [patrickkfkan/volumio-ytcr#14]
I just installed Volumio and the Youtube Cast Receiver plugin and get the following error when I try to cast a song.

```
info: [yt-cast-receiver] Player.play(): U5JxpLOLg3Y @ 0s
info: CoreCommandRouter::volumioGetState
info: CoreCommandRouter::volumioGetState
error: [ytcr] Error in VideoLoader.getInfo(U5JxpLOLg3Y):
(SyntaxError) Unexpected token (1:47)
SyntaxError: Unexpected token (1:47)
    at Parser.pp$4.raise (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp$9.unexpected (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:761:10)
    at Parser.pp$9.semicolon (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:738:68)
    at Parser.pp$8.parseVarStatement (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:1169:10)
    at Parser.pp$8.parseStatement (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:916:19)
    at Parser.pp$8.parseBlock (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:1237:23)
    at Parser.pp$5.parseFunctionBody (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:3286:24)
    at Parser.pp$8.parseFunction (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:1359:10)
    at Parser.pp$8.parseFunctionStatement (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:1059:17)
    at Parser.pp$8.parseStatement (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:904:19)
    at Parser.pp$8.parseTopLevel (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:818:23)
    at Parser.parse (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:590:17)
    at Function.parse (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:640:37)
    at parse (/data/plugins/music_service/ytcr/node_modules/acorn/dist/acorn.js:5567:19)
    at new Jinter (/data/plugins/music_service/ytcr/node_modules/jintr/bundle/jinter.cjs:1029:44)
    at Object.evaluate [as eval] (/data/plugins/music_service/ytcr/node_modules/volumio-youtubei.js/bundle/node.cjs:21633:19)
info: CoreCommandRouter::volumioGetState
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
info: CoreCommandRouter::volumioPushState
```

I'm running Volumio 3.703 and YTCR 1.0.6

**Comment by patrickkfkan** [comment]
Fixed in v1.0.7

https://community.volumio.com/t/plugin-youtube-cast-receiver/46522/282?u=patrickkfkan
