### ISSUE TITLE
Error 410 MPDPlayer when using volumio

### ISSUE THREAD

**Issue by maxdd** [patrickkfkan/volumio-ytcr#8]
Hello Patrick,
i'm still heavily using this amazing plugin but most of the time it gives me headaches, particularly

```
[yt-cast-receiver.YouTubeApp] postBind() completed (ofs: 16)
info: CoreCommandRouter::volumioGetState
[MPDPlayer] Play pln7NWRA1dE at position 0s
[MPDPlayer] is asleep - returning stopped status
[MPDPlayer] loadPlayData(pln7NWRA1dE)
[MPDPlayer] An error occurred while loading track:
Status code: 410
Error: Status code: 410
    at ClientRequest. (/data/plugins/music_service/ytcr/node_modules/miniget/dist/index.js:211:27)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
info: Ignoring MPD Status Update
[MPDPlayer.MPDEventListener] Event received for subsystem 'playlist'
[MPDPlayer.MPDEventListener] Calling handler.handle()...
[MPDPlayer.MPDEventHandler] Number of callbacks for subsystem playlist: 0
```

i'm using youtube vanced but i don't think it is related (because it worked in the past).
What could it be?

Regards,

**Comment by patrickkfkan** [comment]
Looking at the logs, the video you were trying to play is age-restricted. Is this also the case with the other videos that were giving 410 errors? 

I would have to see if there's a solution to this issue.

**Comment by maxdd** [comment]
Actually that was just a coincidence, i've opened the another issue for the "real" problem #9
